name: music_pedometer_ui
description: "A Flutter mobile app that synchronizes music rhythm the the steps of the user."
publish_to: 'none'
version: 1.2.8

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.30
  get: ^4.6.5
  url_launcher: ^6.3.0
  file_picker: ^5.3.1
  package_info_plus: ^8.0.1
  just_audio_background: ^0.0.1-beta.13
  provider: ^6.1.2
  sensors_plus: ^6.0.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.0.9
  syncfusion_flutter_gauges: ^26.2.8
  audio_waveforms: ^1.0.5
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/